{% set name = "allpairspy" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/allpairspy-{{ version }}.tar.gz
  sha256: f69d31a3b56eee119d1ec6063e9c732dd44fbba352ef738cb22d9699fc4009fe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - releasecmd
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - allpairspy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/thombashi/allpairspy
  summary: Pairwise test combinations generator
  dev_url: https://github.com/thombashi/allpairspy
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - apmorton
